//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupComercio.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Archivos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Archivos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SupComercio.Resources.Strings.Archivos", typeof(Archivos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bin/6172746963756c6f73.dat.
        /// </summary>
        internal static string Articulos {
            get {
                return ResourceManager.GetString("Articulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .temp/156789321651354.dat.
        /// </summary>
        internal static string Caja {
            get {
                return ResourceManager.GetString("Caja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bin/656d706c6561646f73.emp.
        /// </summary>
        internal static string Empleado {
            get {
                return ResourceManager.GetString("Empleado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .temp.
        /// </summary>
        internal static string Temporales {
            get {
                return ResourceManager.GetString("Temporales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bin/76616c6573.dat.
        /// </summary>
        internal static string Vales {
            get {
                return ResourceManager.GetString("Vales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventas/Ventas.dat.
        /// </summary>
        internal static string Ventas {
            get {
                return ResourceManager.GetString("Ventas", resourceCulture);
            }
        }
    }
}
