//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupComercio.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SupComercio.Resources.Strings.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advertencia.
        /// </summary>
        internal static string Advertencia {
            get {
                return ResourceManager.GetString("Advertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de argumento invalido.
        /// </summary>
        internal static string ArgumentException {
            get {
                return ResourceManager.GetString("ArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor no puede ser nulo {0} fue null.
        /// </summary>
        internal static string ArgumentNullException {
            get {
                return ResourceManager.GetString("ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de unidad detectado.
        /// </summary>
        internal static string CambioUnidad_caption {
            get {
                return ResourceManager.GetString("CambioUnidad_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se detecto un cambio en el tipo de stock \n¿Desea realizar el cambio?.
        /// </summary>
        internal static string CambioUnidad_message {
            get {
                return ResourceManager.GetString("CambioUnidad_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea cancelar la validacion de licencia?.
        /// </summary>
        internal static string CancelarValidacion {
            get {
                return ResourceManager.GetString("CancelarValidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los siguientes empleados no han marcado asistencia o se encuentran ausentes:\n{0}.
        /// </summary>
        internal static string EmpleadoNoRemovido {
            get {
                return ResourceManager.GetString("EmpleadoNoRemovido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los siguientes empleados ya han marcado asistencia:\n{0}.
        /// </summary>
        internal static string EmpleadosYaIngresados {
            get {
                return ResourceManager.GetString("EmpleadosYaIngresados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha producido un error al finalizar el pago, por favor intentelo nuevamente.
        /// </summary>
        internal static string ErrorFinalizarPago {
            get {
                return ResourceManager.GetString("ErrorFinalizarPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar Ticket.
        /// </summary>
        internal static string GenerarTicket_caption {
            get {
                return ResourceManager.GetString("GenerarTicket_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea generar un ticket?.
        /// </summary>
        internal static string GenerarTicket_message {
            get {
                return ResourceManager.GetString("GenerarTicket_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su Licencia ha caducado o no se ha verificado en mas de 1 año.
        /// </summary>
        internal static string LicenciaVencida {
            get {
                return ResourceManager.GetString("LicenciaVencida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conexion exitosa!.
        /// </summary>
        internal static string MBoxConexionExistosa {
            get {
                return ResourceManager.GetString("MBoxConexionExistosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conexion Fallida IP invalida.
        /// </summary>
        internal static string MBoxConexionFallida {
            get {
                return ResourceManager.GetString("MBoxConexionFallida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Informacion.
        /// </summary>
        internal static string MBoxInfo {
            get {
                return ResourceManager.GetString("MBoxInfo", resourceCulture);
            }
        }
    }
}
