//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupComercio.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringsCierreDeCaja {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsCierreDeCaja() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SupComercio.Resources.Strings.StringsCierreDeCaja", typeof(StringsCierreDeCaja).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debito recibido: $.
        /// </summary>
        internal static string Debito {
            get {
                return ResourceManager.GetString("Debito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Depositos: $.
        /// </summary>
        internal static string Depositos {
            get {
                return ResourceManager.GetString("Depositos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Belgrano XXXX.
        /// </summary>
        internal static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Efectivo recibido: $.
        /// </summary>
        internal static string Efectivo {
            get {
                return ResourceManager.GetString("Efectivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extracciones: $.
        /// </summary>
        internal static string Extracciones {
            get {
                return ResourceManager.GetString("Extracciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fondo de caja entregado: $.
        /// </summary>
        internal static string FCEntregado {
            get {
                return ResourceManager.GetString("FCEntregado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fondo de caja recibido: $.
        /// </summary>
        internal static string FCRecibido {
            get {
                return ResourceManager.GetString("FCRecibido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El negocio.
        /// </summary>
        internal static string NombreComercio {
            get {
                return ResourceManager.GetString("NombreComercio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagos a proveedores: $.
        /// </summary>
        internal static string PagosProveedores {
            get {
                return ResourceManager.GetString("PagosProveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a •Personal a cargo:.
        /// </summary>
        internal static string Personal_Acargo {
            get {
                return ResourceManager.GetString("Personal Acargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a •Personal presente:.
        /// </summary>
        internal static string Personal_Presente {
            get {
                return ResourceManager.GetString("Personal Presente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recaudacion total: $.
        /// </summary>
        internal static string RTotal {
            get {
                return ResourceManager.GetString("RTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sueldos o bonos: $.
        /// </summary>
        internal static string Sueldos {
            get {
                return ResourceManager.GetString("Sueldos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cierre de Caja.
        /// </summary>
        internal static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turno comprendido desde {0} hasta {1}.
        /// </summary>
        internal static string Turno {
            get {
                return ResourceManager.GetString("Turno", resourceCulture);
            }
        }
    }
}
