//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupComercio.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SupComercio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar producto por nombre.
        /// </summary>
        public static string Buscar_Nombre {
            get {
                return ResourceManager.GetString("Buscar_Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apellido no puede quedar vacio.
        /// </summary>
        public static string Error_Apellido {
            get {
                return ResourceManager.GetString("Error_Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad no puede ser 0 (cero) ni negativa.
        /// </summary>
        public static string Error_Cantidad {
            get {
                return ResourceManager.GetString("Error_Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El cargo no puede quedar vacio.
        /// </summary>
        public static string Error_Cargo_Vacio {
            get {
                return ResourceManager.GetString("Error_Cargo_Vacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Celular Invalido.
        /// </summary>
        public static string Error_Celular {
            get {
                return ResourceManager.GetString("Error_Celular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string Error_Codigo {
            get {
                return ResourceManager.GetString("Error_Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña Invalida.
        /// </summary>
        public static string Error_Contraseña_Invalida {
            get {
                return ResourceManager.GetString("Error_Contraseña_Invalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden.
        /// </summary>
        public static string Error_Contraseña_No_Coincide {
            get {
                return ResourceManager.GetString("Error_Contraseña_No_Coincide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuil Invalido.
        /// </summary>
        public static string Error_Cuil {
            get {
                return ResourceManager.GetString("Error_Cuil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La direccion de domicilio no puede quedar vacio.
        /// </summary>
        public static string Error_Domicilio {
            get {
                return ResourceManager.GetString("Error_Domicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a E-mail Invalido.
        /// </summary>
        public static string Error_Email {
            get {
                return ResourceManager.GetString("Error_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: La capacidad de la licencia fue sobrepasada&amp;#xD;&amp;#xA;Comuniquese con soporte tecnico.
        /// </summary>
        public static string Error_Licencia_Capacidad_Sobrepasada {
            get {
                return ResourceManager.GetString("Error_Licencia_Capacidad_Sobrepasada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: La licencia ingresada es invalida.
        /// </summary>
        public static string Error_Licencia_Invalida {
            get {
                return ResourceManager.GetString("Error_Licencia_Invalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Licencia no puede quedar vacia.
        /// </summary>
        public static string Error_Licencia_Vacia {
            get {
                return ResourceManager.GetString("Error_Licencia_Vacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La lista de venta debe contener al menos 1 elemento.
        /// </summary>
        public static string Error_Lista_Ventas_Vacia {
            get {
                return ResourceManager.GetString("Error_Lista_Ventas_Vacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre del producto ya se encuentra registrado.
        /// </summary>
        public static string Error_Nombre_Repetido {
            get {
                return ResourceManager.GetString("Error_Nombre_Repetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre no puede quedar vacio.
        /// </summary>
        public static string Error_Nombre_Vacio {
            get {
                return ResourceManager.GetString("Error_Nombre_Vacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio Invalido.
        /// </summary>
        public static string Error_Precio {
            get {
                return ResourceManager.GetString("Error_Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefono Invalido.
        /// </summary>
        public static string Error_Telefono {
            get {
                return ResourceManager.GetString("Error_Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario ya esta en uso.
        /// </summary>
        public static string Error_Usuario_Repetido {
            get {
                return ResourceManager.GetString("Error_Usuario_Repetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al verificar la licencia los errores fueron: {0}.
        /// </summary>
        public static string ErrorVerificacionLicencia {
            get {
                return ResourceManager.GetString("ErrorVerificacionLicencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Fondo_de_software {
            get {
                object obj = ResourceManager.GetObject("Fondo_de_software", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        public static System.Drawing.Icon icono {
            get {
                object obj = ResourceManager.GetObject("icono", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Icono_Usuario {
            get {
                object obj = ResourceManager.GetObject("Icono_Usuario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar producto por nombre o codigo.
        /// </summary>
        public static string InitBuscNombre {
            get {
                return ResourceManager.GetString("InitBuscNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        public static string InitCantidad_Text {
            get {
                return ResourceManager.GetString("InitCantidad.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo del Producto.
        /// </summary>
        public static string InitCodigo_Text {
            get {
                return ResourceManager.GetString("InitCodigo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad de envases.
        /// </summary>
        public static string InitEnvases {
            get {
                return ResourceManager.GetString("InitEnvases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Producto.
        /// </summary>
        public static string InitNomb_Text {
            get {
                return ResourceManager.GetString("InitNomb.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 00,00.
        /// </summary>
        public static string InitPrecio_Text {
            get {
                return ResourceManager.GetString("InitPrecio.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor.
        /// </summary>
        public static string InitProveedor {
            get {
                return ResourceManager.GetString("InitProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Tilde {
            get {
                object obj = ResourceManager.GetObject("Tilde", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Tilde_Hover {
            get {
                object obj = ResourceManager.GetObject("Tilde_Hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Tilde_Hover_Negro {
            get {
                object obj = ResourceManager.GetObject("Tilde_Hover_Negro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tilde_negro {
            get {
                object obj = ResourceManager.GetObject("tilde_negro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Tilde_Precionado {
            get {
                object obj = ResourceManager.GetObject("Tilde_Precionado", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Tilde_Precionado_Negro {
            get {
                object obj = ResourceManager.GetObject("Tilde_Precionado_Negro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
